Switch back to using yarn

diff --git a/.github/workflows/typescript.yml b/.github/workflows/typescript.yml
--- a/.github/workflows/typescript.yml
+++ b/.github/workflows/typescript.yml
@@ -22,19 +22,27 @@ jobs:
         uses: actions/setup-node@v2
         with:
           node-version: '12'
-          cache: 'npm'
+          cache: 'yarn'
 
       - name: Install NPM packages
-        run: npm install
+        run: yarn install
 
       - name: Format Check
-        run: npm run format-check
+        run: yarn run format-check
 
       - name: Link
-        run: npm run lint
+        run: yarn run lint
 
       - name: Test
-        run: npm test
+        run: yarn test
+
+      - name: Compare the expected and actual dist/ directories
+              run: |
+                if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
+                  echo "::error:: Detected uncommitted changes after build.  See status below:"
+                  git diff
+                  exit 1
+                fi
       # - name: Test with Buildx
       #   uses: docker/bake-action@v1.7.0
       #   with:
